<?xml version="1.0" encoding="utf-8"?><Database Name="BookshopBranch" Class="BooksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\v11.0;Initial Catalog=BookshopBranch;Integrated Security=True" SettingsObjectName="Rest.Data.Properties.Settings" SettingsPropertyName="BookshopBranchConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Author" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Category" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Language" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Author_Book" Member="Author" ThisKey="Id_Author" OtherKey="Id" Type="Author" IsForeignKey="true" />
      <Association Name="Category_Book" Member="Category" ThisKey="Id_Category" OtherKey="Id" Type="Category" IsForeignKey="true" />
      <Association Name="Language_Book" Member="Language" ThisKey="Id_Language" OtherKey="Id" Type="Language" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Authors" Member="Authors">
    <Type Name="Author">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Author_Book" Member="Books" ThisKey="Id" OtherKey="Id_Author" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Book" Member="Books" ThisKey="Id" OtherKey="Id_Category" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Languages" Member="Languages">
    <Type Name="Language">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Language" Member="Language1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Language_Book" Member="Books" ThisKey="Id" OtherKey="Id_Language" Type="Book" />
    </Type>
  </Table>
</Database>